- greendoor/asgi.py
- greendoor/settings.py
- greendoor/urls.py
- greendoor/wsgi.py
- manage.py
- poetry.lock
- pyproject.toml
> 추가 - code formatter BLACK 실행 명령어:poetry run black .

- feed/services/feed_service.py
- greendoor/settings.py
- poetry.lock
- pyproject.toml
- templates/password/password_reset.html
- templates/password/password_reset_complete.html
- templates/password/password_reset_confirm.html
- templates/password/password_reset_done.html
- user/urls.py
- user/views.py
비밀번호 리셋 
메일 전송 기능
django-crispy-forms 패키지 설치
#33
> feature 병합 product (비밀번호 리셋 메일 전송 기능)

- cart/forms.py
- cart/urls.py
- cart/views.py
- config/settings.py
- config/urls.py
- feed/services/feed_service.py
- feed/views.py
- product/models.py
- product/urls.py
- product/views.py
- user/admin.py
- user/forms.py
- user/urls.py
- user/views.py
#35
유저 프로필 편집 기능 부분 머지
forms.py 생성
user 모델 어드민 연결
config url - user url 연결
> 추가 - user profile edit forms.py

- config/urls.py
- user/forms.py
- user/models.py
- user/services/userimg_service.py
- user/views.py
Image
user profile image 코드 작업 진행
> user profile image 코드 작업 진행

- feed/views.py
- templates/feeddetail.html
> 수정 - 커뮤니티앱 index, feeddetail 백 - 프론트 연결 작업 wip:

- templates/mypage.html
- templates/password/password_reset_complete.html
- user/urls.py
- user/views.py
mypage.html 함수 연결(2차) 코드 진행
개인 페이지 다른 사용자 접근 금지 코드 추가
./test.sh
> 수정 - mypage.html 함수 연결(2차) 코드 진행

- templates/user_test/edit.html
add -  js code
edit.html 프로필 변경 이미지 미리보기 기능 추가 (js)
./tset.sh
> html 함수 연결(3차) 진행코드

- templates/user_test/edit.html
user profile image 미리보기 
빠진 코드 추가
> 추가 - 이미지 미리보기 js 코드 추가

- templates/password/password_reset_complete.html
- user/urls.py
- user/views.py
> 수정 - user app url

- user/views.py
> 수정3 - user app url 수정

- templates/password/password_reset.html
- templates/password/password_reset_complete.html
- templates/password/password_reset_confirm.html
- templates/password/password_reset_done.html
- templates/user_test/edit.html
> 수정 - profile_edit

- templates/password/password_reset.html
- templates/password/password_reset_complete.html
- templates/password/password_reset_confirm.html
- templates/password/password_reset_done.html
- templates/user_test/edit.html
> 수정 - profile_edit 부트스트랩

- templates/mypage.html
> 수정 - 임시 마이페이지 CSS

- user/forms.py
- user/models.py
- user/views.py
수정 - User app foms.py 필드 한글명으로
> 수정 - User app foms.py 필드 한글명으로

- user/forms.py
- user/models.py
- user/views.py
> 수정 - 경로 수정 User app edit

- static/css/mypage.css
- static/css/password_reset_confirm.css
- static/css/profileedit.css
- templates/mypage.html
- templates/user_test/edit.html
> Test_greendoor branch 최종 병합

- user/forms.py
- user/views.py
추가 - username 필드 유효성검사
./test.sh
> 추가 - username 필드 유효성검사

- user/services/signup_service.py
- user/views.py
추가 - signup_service.py 
password, username 유효성 검사 함수
./test.py
> 추가 - signup_service.py

- templates/user_test/edit.html
> 수정 - 미리보기 js CSS

- templates/mypage.html
mypage.html 
{{ user.nickname }} -> {{ user.username }} 변경
> 수정 - mypage.html username

- static/css/feedindex.css
- templates/mypage.html
mypage.html title 커뮤니티 -> 마이페이지
인덱스페이지 이미지 마진, 가로길이 수정
> 수정 - mypage.html title 등

- static/css/feeddetail.css
> 수정 - 디테일페이지CSS

- product/views.py
- templates/product/list.html
> 추가 - 페이지네이션 기능 #113

- static/js/edit.js
- templates/password/password_reset.html
- templates/user_test/edit.html
- user/views.py
> 수정 - user profile Image edit
